(function($){$.fn.hasAttr=function(name){return this.attr(name)!==undefined};$.checkvalue=function(container,value){if(typeof container==='string'){return container==value}
else{return container.indexOf(value)>-1}}
$.ChoiceExInitialized=function($form,fieldName,options,validate){var choicefield=options.choicefield||'',choicevalue=options.choicevalue||'',choicetype=options.choicetype||'radio',isdisabled=options.disabled||!1;var choiceselected=$('[name="'+fieldName+'"]'+(choicetype.toLowerCase()=="select"?' option:selected':':checked')).val();var fieldobject=$('[name="'+choicefield+'"]');var attr=fieldobject.attr('disabled');if(!$.checkvalue(choicevalue,choiceselected)){if(validate)$form.formValidation('resetField',fieldobject);fieldobject.val('');if(isdisabled){if(typeof attr===typeof undefined){fieldobject.attr('disabled',!0)}}
else{fieldobject.hide()}}
if($.checkvalue(choicevalue,choiceselected)){if(isdisabled){if(typeof attr!==typeof undefined){fieldobject.removeAttr('disabled')}}
else{fieldobject.show()}
if(validate)$form.formValidation('revalidateField',choicefield)}}})(jQuery);(function($){FormValidation.Validator.dateex={html5Attributes:{monthfield:'monthfield',dayfield:'dayfield',yearfield:'yearfield',},init:function(validator,$field,options){var $form=validator.getForm(),fieldName=$field.attr('data-fv-field'),monthfield=options.monthfield||'',dayfield=options.dayfield||'',yearfield=options.yearfield||'';var DateExInitialized=function($form,fieldName,yearfield,monthfield,dayfield){var y=$form.find('[name="'+yearfield+'"]').val(),m=$form.find('[name="'+monthfield+'"] option:selected').val(),d=((dayfield.length>0)?$form.find('[name="'+dayfield+'"]').val():'01');$form.find('[name="'+fieldName+'"]').val(y===''||m===''||d===''?'':[d,m,y].join('/'));$form.formValidation('revalidateField',fieldName)}
if(monthfield.length>0&&yearfield.length>0){$form.find('[name="'+monthfield+'"]').change(function(){DateExInitialized($form,fieldName,yearfield,monthfield,dayfield)});$form.on('input','[name="'+yearfield+'"]',function(){DateExInitialized($form,fieldName,yearfield,monthfield,dayfield)});if(dayfield.length>0){$form.on('input','[name="'+dayfield+'"]',function(){DateExInitialized($form,fieldName,yearfield,monthfield,dayfield)})}}},validate:function(validator,$field,options){var $form=validator.getForm(),fieldName=$field.attr('data-fv-field'),monthfield=options.monthfield||'',dayfield=options.dayfield||'',yearfield=options.yearfield||'';var y=$form.find('[name="'+yearfield+'"]').val(),m=$form.find('[name="'+monthfield+'"] option:selected').val(),d=((dayfield.length>0)?$form.find('[name="'+dayfield+'"]').val():'01');if(y.length==0&&m.length==0&&((dayfield.length>0)?d.length==0:!0)){return!0}
else{return $field.val()!==''}}}})(jQuery);(function($){FormValidation.Validator.ChoiceEx={html5Attributes:{message:'message',choicevalue:'choicevalue',choicefield:'choicefield',choicetype:'choicetype',disabled:'disabled'},init:function(validator,$field,options,e){var $form=validator.getForm(),fieldName=$field.attr('data-fv-field'),choicefieldname=options.choicefield||'';if(choicefieldname.length>0){validator.onLiveChange($field,"live_"+e,function(){$.ChoiceExInitialized($form,fieldName,options,!0)});$.ChoiceExInitialized($form,fieldName,options,!1)}},destroy:function(validator,$field,options){validator.offLiveChange($field,"live_"+e)},validate:function(validator,$field,options){return!0}}})(jQuery);(function($){FormValidation.Validator.eitherOne={html5Attributes:{message:"message",field:"field"},validate:function(validator,$field,options,event){var value=$field.val();var otherfieldhasvalue=!1;if(typeof options.field!==typeof undefined){otherfieldvalidator=validator.getFieldElements(options.field);otherfieldhasvalue=(otherfieldvalidator.val()!=='');var otherstatus=validator.getStatus(otherfieldvalidator,event);if(value===''&&!otherfieldhasvalue){validator.updateStatus(otherfieldvalidator,validator.STATUS_INVALID,event)}
else if(value!==''&&!otherfieldhasvalue){validator.updateStatus(otherfieldvalidator,validator.STATUS_VALID,event)}}
return value!==''||otherfieldhasvalue}}})(jQuery)